# Main code file
from utils import *
from covid import *

# Load in the data from the GitHub repository and reformat it for use with our
# statistical libraries. Note: this depends on your repository being in the same
# directory as your data.
#df = loadAndCleanData("COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
#3:
df = loadAndCleanData("time_series_covid19_confirmed_global.csv")

#5:
df = correctDateFormat(df)
print(df)


# Print a graph of the confirmed cases over time and the confirmed cases across
# countries over time. Keep in mind that uncertainty as shown in these graphs
# corresponds to variation over different regions in the country, *not*
# actual uncertainty in the sample, which may come from a variety of sources.
#plotTimeline(df, "Date", "Confirmed")
#plotMultipleTimelines(df, "Date", "Confirmed", "Country/Region")


# Use these variables so it's easy to change up what columns you look at
# These just reference the column name
x = "Date"
y = "Confirmed"

#7:
df1 = loadAndCleanData("time_series_covid19_deaths_global.csv")
df2 = loadAndCleanData("time_series_covid19_recovered_global.csv")

#9:
x = mergeData(x, df2, "Recovered")
print(mergeData(x, df2, "Recovered"))
y = mergeData(df, df1, "Deaths")
print(mergeData(df, df1, "Deaths"))

#11:
plotTimeline(x, "Date", "Confirmed")
plotTimeline(y, "Date", "Deaths")
plotTimeline(z, "Date", "Recovered")
# Run a linear regression on our covid data
# This will look at the covid data for each row of the pivoted dataset
# and will print the equation generated by the model.
# Note the R2 here: this model isn't very good--it basically predicts 0 because
# the data is heavily time-varying, meaning lots of 0 datapoints early in the
# dataset from before the country reached it.
linearModel = runTemporalLinearRegression(df, x, y)
print("y = " + str(linearModel[0]) + "x + " + str(linearModel[1]))

# To get a better prediction, let's aggregate all cases, so we have one count
# per date. Look at the sum total cases over the entire world.
groupedDf = df.groupby(x, as_index=False).sum()
linearModel = runTemporalLinearRegression(groupedDf, x, y)
print("y_world = " + str(linearModel[0]) + "x + " + str(linearModel[1]))

# We can see that things are still a bit skewed: we're starting to see that
# exponential piece of the curve take off. We can try to take the log of the
# data column to model the growth rate (e^m will give that to us). np math
# operations apply to the whole column, so that would look like this:
groupedDf["Confirmed"] = np.log(groupedDf["Confirmed"])
linearModel = runTemporalLinearRegression(groupedDf, x, y)
print("y_world = " + str(linearModel[0]) + "x + " + str(linearModel[1]))

# We can see that the exponential curve still isn't a great model for the world:
# we're still collecting data and the general population is still in the exponential
# part of the growth curve. Let's take a look at an individual country, Italy.
# We can pull out Italy's data, remove any 0 entries, and look at the model.
italyData = groupByCountry(df, "Italy")
italyData = italyData[italyData["Confirmed"] > 3]
italyData["Confirmed"] = np.log(italyData["Confirmed"])
linearModel = runTemporalLinearRegression(italyData, x, y)
print("y_italy = " + str(linearModel[0]) + "x + " + str(linearModel[1]))
italyGrowth = math.exp(linearModel[0])
print("Italy's Growth Rate is " + str(italyGrowth))

# Model the growth rate in the US. Note that the best way to model lots of
# growth rates would be to define a computeGrowthRate function in covid.py.
usData = groupByCountry(df, "US")
usData = usData[usData["Confirmed"] > 3]
usData["Confirmed"] = np.log(usData["Confirmed"])
linearModel = runTemporalLinearRegression(usData, x, y)
print("y_us = " + str(linearModel[0]) + "x + " + str(linearModel[1]))
usGrowth = math.exp(linearModel[0])
print("US's Growth Rate is " + str(usGrowth))

# Model the disease spread in China. China has reached the top of the logistic
# curve, so it doesn't make sense to use a linear model any more. Instead, we're
# going to fit the data to a logistic function. 
chinaData = groupByCountry(df, "China")
#linearModel = runTemporalLinearRegression(chinaData, x, y)
logisticModel = runTemporalLogisticRegression(chinaData, x, y)
print("y_china = 1 / (1 + e^-(" + str(logisticModel[1]) + "x + " + str(logisticModel[2]) + "))")
